window.categories = {
    "data": [
        {
            "id": "5d745101-7a67-4127-b901-56debe05f3c8",
            "slug": "construccion",
            "name": "Construcción",
            "icon_slug": "arquitecto",
            "parent_id": null,
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "336309b7-d4aa-4783-aa24-21703613cc4b",
            "slug": "salud",
            "name": "Salud",
            "icon_slug": "medico",
            "parent_id": null,
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "6eed8f9b-3a45-4211-9cb0-46f7665f86c1",
            "slug": "tecnologia",
            "name": "Tecnología",
            "icon_slug": "analista_sistemas",
            "parent_id": null,
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "52ff6140-d7de-45f7-bd7b-fbc1fa916705",
            "slug": "educacion",
            "name": "Educación",
            "icon_slug": "profesor",
            "parent_id": null,
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "f5eb45a3-6c9d-4fd0-8187-55c616fa38d1",
            "slug": "hogar",
            "name": "Hogar",
            "icon_slug": "cocinero",
            "parent_id": null,
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "1b52502b-16d8-49c3-b279-77fa3d83e0e3",
            "slug": "belleza",
            "name": "Belleza",
            "icon_slug": "cosmetologo",
            "parent_id": null,
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "18a7ead3-9e16-4b75-a7e3-04b395f42280",
            "slug": "legal",
            "name": "Legal",
            "icon_slug": "abogado",
            "parent_id": null,
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "d1efa13b-7c16-4854-a01a-887b6aad438a",
            "slug": "finanzas",
            "name": "Finanzas",
            "icon_slug": "contador",
            "parent_id": null,
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "7fe9797e-4fb8-44d3-bb97-a38ec4271547",
            "slug": "arte",
            "name": "Arte",
            "icon_slug": "pintor",
            "parent_id": null,
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "2c1355f2-2761-45cc-99f3-4bfaa99eb74f",
            "slug": "deportes",
            "name": "Deportes",
            "icon_slug": "deportistas",
            "parent_id": null,
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "8af41d97-3d8c-4cb0-9e0f-9d2e34991f17",
            "slug": "ciencias",
            "name": "Ciencias",
            "icon_slug": "biologo",
            "parent_id": null,
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "10b91a59-9e32-4aac-ae33-4c9f534659fe",
            "slug": "textil",
            "name": "Textil",
            "icon_slug": "costurera",
            "parent_id": null,
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "6f27095a-9e1b-4bcb-aec6-8c4a0e487287",
            "slug": "transporte",
            "name": "Transporte",
            "icon_slug": "conductor",
            "parent_id": null,
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "1cd876d4-21ed-4173-89fd-e516eeb25504",
            "slug": "administracion",
            "name": "Administración",
            "icon_slug": "administrador_empresas",
            "parent_id": null,
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "6d092d57-c4da-44d0-a631-f71350475e43",
            "slug": "locutor",
            "name": "Locutor",
            "icon_slug": "locutor",
            "parent_id": null,
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "c6fcc197-a14d-4803-8c52-138cf90f8690",
            "slug": "modelo",
            "name": "Modelo",
            "icon_slug": "modelo",
            "parent_id": null,
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "0df39de8-46a4-4443-a381-a0b7c155ad25",
            "slug": "obstetra",
            "name": "Obstetra",
            "icon_slug": "obstetra",
            "parent_id": null,
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "61e01e98-561f-450d-bd62-24ee5df11df1",
            "slug": "radio_tecnico",
            "name": "Radio Técnico",
            "icon_slug": "radio_tecnico",
            "parent_id": null,
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "ed804967-3339-47e4-8d30-00c347550652",
            "slug": "Tapicero",
            "name": "Tapicero",
            "icon_slug": "Tapicero",
            "parent_id": null,
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "86121941-45e7-4037-ad57-c01226075e82",
            "slug": "coreografo",
            "name": "Coreógrafo",
            "icon_slug": "coreografo",
            "parent_id": null,
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "be92d575-59f6-42ed-9951-e15ff7ddf0cd",
            "slug": "escenografo",
            "name": "Escenógrafo",
            "icon_slug": "escenografo",
            "parent_id": null,
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "2eca0850-b532-4e8c-a0d7-a71f16c8b2c5",
            "slug": "farmacologo",
            "name": "Farmacólogo",
            "icon_slug": "farmacologo",
            "parent_id": null,
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "f3556874-61d1-44d2-9acf-e80818ee652a",
            "slug": "albanil",
            "name": "Albañil",
            "icon_slug": "albanil",
            "parent_id": "5d745101-7a67-4127-b901-56debe05f3c8",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "d5f71983-3256-45f7-a33e-0cd387861fa8",
            "slug": "carpintero",
            "name": "Carpintero",
            "icon_slug": "carpintero",
            "parent_id": "5d745101-7a67-4127-b901-56debe05f3c8",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "d041ebea-8c89-42b9-95ef-3739be0803d0",
            "slug": "electricista",
            "name": "Electricista",
            "icon_slug": "electricista",
            "parent_id": "5d745101-7a67-4127-b901-56debe05f3c8",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "d5e78b25-9393-4a27-9171-5adba63430c8",
            "slug": "gasfitero",
            "name": "Gasfitero",
            "icon_slug": "gasfitero",
            "parent_id": "5d745101-7a67-4127-b901-56debe05f3c8",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "a7744297-317d-48f3-af03-a348969c8f96",
            "slug": "pintor",
            "name": "Pintor",
            "icon_slug": "pintor",
            "parent_id": "5d745101-7a67-4127-b901-56debe05f3c8",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "d46ccf85-b7fa-4aee-8c6f-a9c2acef162a",
            "slug": "soldador",
            "name": "Soldador",
            "icon_slug": "soldador",
            "parent_id": "5d745101-7a67-4127-b901-56debe05f3c8",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "f9c4ea72-4708-45e9-8300-a93798b44e04",
            "slug": "medico",
            "name": "Médico",
            "icon_slug": "medico",
            "parent_id": "336309b7-d4aa-4783-aa24-21703613cc4b",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "198edc07-d0e3-44ca-8e0d-a79cb886b0f2",
            "slug": "enfermero",
            "name": "Enfermero",
            "icon_slug": "enfermero",
            "parent_id": "336309b7-d4aa-4783-aa24-21703613cc4b",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "91a7e2c7-6b48-486a-9a9c-d036217583dc",
            "slug": "odontologo",
            "name": "Odontólogo",
            "icon_slug": "odontologo",
            "parent_id": "336309b7-d4aa-4783-aa24-21703613cc4b",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "f4ab8e30-496b-43a0-9d65-36a6c36f40ea",
            "slug": "psicologo",
            "name": "Psicólogo",
            "icon_slug": "psicologo",
            "parent_id": "336309b7-d4aa-4783-aa24-21703613cc4b",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "dc305172-5fa9-4fcb-a156-1716391cab71",
            "slug": "nutricionista",
            "name": "Nutricionista",
            "icon_slug": "nutricionista",
            "parent_id": "336309b7-d4aa-4783-aa24-21703613cc4b",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "f6f69223-fbe1-43d5-a034-14ae906686cd",
            "slug": "veterinario",
            "name": "Veterinario",
            "icon_slug": "veterinario",
            "parent_id": "336309b7-d4aa-4783-aa24-21703613cc4b",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "ecdc0cc5-16e0-410f-b6af-50140cd6a23a",
            "slug": "farmaceutico",
            "name": "Farmacéutico",
            "icon_slug": "farmaceutico",
            "parent_id": "336309b7-d4aa-4783-aa24-21703613cc4b",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "d3081363-c859-4ba7-ac9b-11dc8ef17646",
            "slug": "ingeniero",
            "name": "Ingeniero",
            "icon_slug": "ingeniero",
            "parent_id": "6eed8f9b-3a45-4211-9cb0-46f7665f86c1",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "f390e37f-6a44-40a7-bb73-6b44a86b42d8",
            "slug": "analista_sistemas",
            "name": "Analista de Sistemas",
            "icon_slug": "analista_sistemas",
            "parent_id": "6eed8f9b-3a45-4211-9cb0-46f7665f86c1",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "42ab68e2-04ba-483c-bf56-87f8f7b76c27",
            "slug": "disenador",
            "name": "Diseñador",
            "icon_slug": "disenador",
            "parent_id": "6eed8f9b-3a45-4211-9cb0-46f7665f86c1",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "929ad32d-6416-4440-83fa-ec0e87356d9e",
            "slug": "tecnico",
            "name": "Técnico",
            "icon_slug": "tecnico",
            "parent_id": "6eed8f9b-3a45-4211-9cb0-46f7665f86c1",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "ee89256b-ce06-4686-8dce-342249cae267",
            "slug": "profesor",
            "name": "Profesor",
            "icon_slug": "profesor",
            "parent_id": "52ff6140-d7de-45f7-bd7b-fbc1fa916705",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "ad2e62d5-0331-4131-abd8-5e23684ee18f",
            "slug": "traductor",
            "name": "Traductor",
            "icon_slug": "traductor",
            "parent_id": "52ff6140-d7de-45f7-bd7b-fbc1fa916705",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "b6453f5b-7ed3-4f34-8504-05cd58ad2235",
            "slug": "escritor",
            "name": "Escritor",
            "icon_slug": "escritor",
            "parent_id": "52ff6140-d7de-45f7-bd7b-fbc1fa916705",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "cd572f65-625d-49ad-8be1-0d23f265b493",
            "slug": "periodista",
            "name": "Periodista",
            "icon_slug": "periodista",
            "parent_id": "52ff6140-d7de-45f7-bd7b-fbc1fa916705",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "56dbdf44-8337-42ff-85ee-31cc902149ec",
            "slug": "cocinero",
            "name": "Cocinero",
            "icon_slug": "cocinero",
            "parent_id": "f5eb45a3-6c9d-4fd0-8187-55c616fa38d1",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "8d7fcd50-551a-489b-befd-8cf9adcf5b44",
            "slug": "jardinero",
            "name": "Jardinero",
            "icon_slug": "jardinero",
            "parent_id": "f5eb45a3-6c9d-4fd0-8187-55c616fa38d1",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "cee238f1-d8c8-4c1e-a807-3447a72274d8",
            "slug": "estibador",
            "name": "Estibador",
            "icon_slug": "estibador",
            "parent_id": "f5eb45a3-6c9d-4fd0-8187-55c616fa38d1",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "7539e082-f0ab-4c31-af56-73095c0cf5a7",
            "slug": "mecanico",
            "name": "Mecánico",
            "icon_slug": "mecanico",
            "parent_id": "f5eb45a3-6c9d-4fd0-8187-55c616fa38d1",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "a2a849e9-6cf4-4750-9f9f-6bbe75b4b885",
            "slug": "peluqueria",
            "name": "Peluquería",
            "icon_slug": "peluqueria",
            "parent_id": "1b52502b-16d8-49c3-b279-77fa3d83e0e3",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "9c9b37e8-2f29-4aa1-9229-ab66865055d0",
            "slug": "cosmetologo",
            "name": "Cosmetólogo",
            "icon_slug": "cosmetologo",
            "parent_id": "1b52502b-16d8-49c3-b279-77fa3d83e0e3",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "b731fb66-45a1-4a27-a698-2084b97907aa",
            "slug": "barbero",
            "name": "Barbero",
            "icon_slug": "barbero",
            "parent_id": "1b52502b-16d8-49c3-b279-77fa3d83e0e3",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "ea4ba4d1-4a37-429b-8e58-e53de0318a5a",
            "slug": "abogado",
            "name": "Abogado",
            "icon_slug": "abogado",
            "parent_id": "18a7ead3-9e16-4b75-a7e3-04b395f42280",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "87c2ec5d-1b0e-4f16-827d-2aa2bf944853",
            "slug": "sindico",
            "name": "Síndico",
            "icon_slug": "sindico",
            "parent_id": "18a7ead3-9e16-4b75-a7e3-04b395f42280",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "c9cc06d0-bfb2-4c63-884f-0733264313c0",
            "slug": "contador",
            "name": "Contador",
            "icon_slug": "contador",
            "parent_id": "d1efa13b-7c16-4854-a01a-887b6aad438a",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "6e2da373-9fd1-415a-9804-863843f64dc4",
            "slug": "economista",
            "name": "Economista",
            "icon_slug": "economista",
            "parent_id": "d1efa13b-7c16-4854-a01a-887b6aad438a",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "eb83c924-4713-47ce-93ae-8802b33155ad",
            "slug": "fotografo",
            "name": "Fotógrafo",
            "icon_slug": "fotografo",
            "parent_id": "7fe9797e-4fb8-44d3-bb97-a38ec4271547",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "9ad9b632-b77d-4aa1-8ca4-7538b86753fa",
            "slug": "musico",
            "name": "Músico",
            "icon_slug": "musico",
            "parent_id": "7fe9797e-4fb8-44d3-bb97-a38ec4271547",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "5f417551-fb5d-4063-ba6b-802f6d9b705a",
            "slug": "actor",
            "name": "Actor",
            "icon_slug": "actor",
            "parent_id": "7fe9797e-4fb8-44d3-bb97-a38ec4271547",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "48ac2532-f8e7-47f5-96c8-aa3fb12b1892",
            "slug": "escultor",
            "name": "Escultor",
            "icon_slug": "escultor",
            "parent_id": "7fe9797e-4fb8-44d3-bb97-a38ec4271547",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "2529c900-5b4e-4995-9b2c-da996732bc82",
            "slug": "artesano",
            "name": "Artesano",
            "icon_slug": "artesano",
            "parent_id": "7fe9797e-4fb8-44d3-bb97-a38ec4271547",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "e0e5e95b-b2c1-486b-8209-e886c69f3148",
            "slug": "entrenador",
            "name": "Entrenador",
            "icon_slug": "entrenador",
            "parent_id": "2c1355f2-2761-45cc-99f3-4bfaa99eb74f",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "c61e1fd1-c0e4-4100-ab12-da6f40ae2f98",
            "slug": "agronomo",
            "name": "Agrónomo",
            "icon_slug": "agronomo",
            "parent_id": "8af41d97-3d8c-4cb0-9e0f-9d2e34991f17",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "e22a86f1-bb95-4b71-b24f-7cbaa4bb98b3",
            "slug": "geografo",
            "name": "Geógrafo",
            "icon_slug": "geografo",
            "parent_id": "8af41d97-3d8c-4cb0-9e0f-9d2e34991f17",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "b5b3831b-0ff0-42a7-90c2-ba9b6d2877db",
            "slug": "costurera",
            "name": "Costurera",
            "icon_slug": "costurera",
            "parent_id": "10b91a59-9e32-4aac-ae33-4c9f534659fe",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "6a522ed3-72cf-4caa-a629-9dde1a75529e",
            "slug": "sastre",
            "name": "Sastre",
            "icon_slug": "sastre",
            "parent_id": "10b91a59-9e32-4aac-ae33-4c9f534659fe",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        {
            "id": "6b53cfea-e8c4-429a-82ce-df6adf0727a2",
            "slug": "joyero",
            "name": "Joyero",
            "icon_slug": "joyero",
            "parent_id": "6f27095a-9e1b-4bcb-aec6-8c4a0e487287",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        },
        // {
        //     "id": "d0872979-4ede-4d49-8e3c-5dab88528bb7",
        //     "slug": "gestor-de-negocios",
        //     "name": "Gestor de Negocios",
        //     "icon_slug": "gestor-de-negocios",
        //     "parent_id": "1cd876d4-21ed-4173-89fd-e516eeb25504",
        //     "is_active": true,
        //     "is_public": true,
        //     "requires_certification": false,
        //     "job_count": 0,
        //     "worker_count": 0
        // },
        {
            "id": "04cbb4cd-c09e-4190-be29-35e9c2860f0c",
            "slug": "sociologo",
            "name": "Sociólogo",
            "icon_slug": "sociologo",
            "parent_id": "1cd876d4-21ed-4173-89fd-e516eeb25504",
            "is_active": true,
            "is_public": true,
            "requires_certification": false,
            "job_count": 0,
            "worker_count": 0
        }
    ],
    "count": 67
}